#put any key/value pairs here
my.plugin.name=MyPlugin
bookstore.project.section.label=Bookstore tools
bookstore.project.users.label=Project users
project-users-servlet.name=Project Users Servlet
project-users-servlet.description=Shows users who can browse the project
project-users-web-work.name=Project Users WebWork
project-users-web-work.description=The Project Users WebWork Plugin
edit-user-groups-action.name=Edit User Groups Action
edit-user-groups-action.description=The Edit User Groups Action Plugin
listofusers.name=List of users
listofusers.description=Shows all users who can browse the project
